name: Gửi Thông Báo Discord

on:
  push: # Kích hoạt khi có push
  pull_request: # Kích hoạt khi có pull request (tùy chọn)

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Gửi thông báo tới Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }} # Lưu URL webhook trong Secrets
        run: |
          # Lấy thông tin từ GitHub event
          PUSHER_NAME="${{ github.actor }}"
          REPO_NAME="${{ github.repository }}"
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          COMMIT_ID=$(git log -1 --pretty=%h)

          # Tạo nội dung thông báo bằng tiếng Việt
          MESSAGE="**Thông báo từ GitHub**\n"
          MESSAGE+="Người thực hiện: **${PUSHER_NAME}**\n"
          MESSAGE+="Repository: **${REPO_NAME}**\n"
          MESSAGE+="Thay đổi mới nhất: \n- ${COMMIT_MESSAGE} (Commit ID: ${COMMIT_ID})"

          # Gửi thông báo qua webhook
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"${MESSAGE}\" }" \
            "$DISCORD_WEBHOOK"
